defaults:
  - _self_
  - model: xgboost
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

experiment_name: "xG_Optuna_Optimization"

data:
  features_path: "data/processed/features.csv"
  labels_path: "data/processed/labels.csv"

# Optuna Configuration
hydra:
  sweeper:
    sampler:
      seed: 123
    direction: maximize  # We want to MAXIMIZE AUC
    study_name: xgboost_optimization
    n_trials: 10         # Start with 10 trials to test
    n_jobs: 1            # Keep 1 to avoid conflicts
    
    # The Search Space
    params:
      model.params.learning_rate: interval(0.01, 0.3)
      model.params.max_depth: choice(3, 4, 5, 6, 8)
      model.params.n_estimators: choice(100, 200, 300, 500)